// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwLhxqIgzSEx8c_EYyKVDwkWl5Eud9hKY',
    appId: '1:413685409021:web:dee6b5f95e208ff5610a94',
    messagingSenderId: '413685409021',
    projectId: 'megahertzmainwebsite',
    authDomain: 'megahertzmainwebsite.firebaseapp.com',
    storageBucket: 'megahertzmainwebsite.firebasestorage.app',
    measurementId: 'G-HF76PDPBBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWEcPbrc1t9bZS7eO4Q9o2h7lCoHkCO5s',
    appId: '1:413685409021:android:c7652865a54dc22d610a94',
    messagingSenderId: '413685409021',
    projectId: 'megahertzmainwebsite',
    storageBucket: 'megahertzmainwebsite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7aS0n-bMkOIhWn3EqJJ32Jr5rSIwImtk',
    appId: '1:413685409021:ios:805edc2c87d8457f610a94',
    messagingSenderId: '413685409021',
    projectId: 'megahertzmainwebsite',
    storageBucket: 'megahertzmainwebsite.firebasestorage.app',
    iosBundleId: 'com.example.megahertzRobotics',
  );
}
